# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest with xgboost

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,windows-latest, macos-latest,]
        python-version: [3.8, ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -r requirements.txt xgboost cython igraph pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Build extensions
      run: |
        python setup.py build_ext --inplace
#    - name: set environment variables
#      uses: allenevans/set-env@v2.0.0
#      with:
#        FOO_PYTHONPATH: '.'
    - name: Dump environment variables
      run: |
        python -c "import os;list(map(print,os.environ.items()))"
    - name: Test with pytest
      run: |
        pytest --cov=ylearn --durations=30
